AccountsApp/urls.py
from django.urls import path
from . import views

app_name = 'AccountsApp'

urlpatterns = [
    path('', views.LoginView, name = 'login'),
    path('logout/', views.LogoutView, name = 'logout')
]

App/urls.py
from django.urls import path
from . import views

app_name = 'App'

urlpatterns = [
    path('', views.HomeView, name = 'home'),
    path('bot/<str:id>', views.SelectBotView, name = 'select-bot'),
    path('speaker/on/<str:id>', views.SpeakerONStautsView, name = 'speaker-on'),
    path('speaker/off/<str:id>', views.SpeakerOFFStatusView, name = 'speaker-off'),

    path('vbot/<str:id>', views.SelectVBBotView, name = 'select-vbot'),
    path('bot-status/<str:id>', views.Botstatus, name = 'bot-status'),

]

WB_Project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('AccountsApp.urls')),
    path('app/', include('App.urls')),
    path('api/', include('api.urls'))
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>
        {% block title %}{% endblock%} {{rest|title}}
  </title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static "assets/img/apple-touch-icon.png" %}" rel="apple-touch-icon">
  
  <link href="{% static "assets/img/favicon-.png" %}" rel="icon">
  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static "assets/vendor/aos/aos.css" %}" rel="stylesheet">
  <link href="{% static "assets/vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">
  <link href="{% static "assets/vendor/bootstrap-icons/bootstrap-icons.css" %}" rel="stylesheet">
  <link href="{% static "assets/vendor/boxicons/css/boxicons.min.css" %}" rel="stylesheet">
  <link href="{% static "assets/vendor/glightbox/css/glightbox.min.css" %}" rel="stylesheet">
  <link href="{% static "assets/vendor/remixicon/remixicon.css" %}" rel="stylesheet">
  <link href="{% static "assets/vendor/swiper/swiper-bundle.min.css" %}" rel="stylesheet">

  <link rel="stylesheet" href="{% static "assets/vendor/sweetalert2/dist/sweetalert2.min.css" %}">

  <!-- Template Main CSS File -->
  <link href="{% static "assets/css/style.css" %}" rel="stylesheet">
  <link href="{% static "assets/css/style1.css" %}" rel="stylesheet">


  {% block css %}
  {% endblock %}
<script src="{% static "assets/js/bootstrap.min.js" %}"></script>
<script src="{% static "assets/js/jquery.min.js" %}"></script>
<!------ Include the above in your HEAD tag ---------->

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" />




<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top">
    <div class="container d-flex align-items-center justify-content-between">

    
      <a href=""><img src="/static{{rest.rest_logo.url}}" alt="{{rest.rest_name}}"></a>      
     
      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto " href="{% url 'App:home' %}">Home</a></li>
          
          <li class="dropdown">
            <a href="#">
              <span>status</span>
              <!-- <i class="bi bi-chevron-down"> -->
              </i>
            </a>
            <ul>
              {% for i in cp_bots %}
              <li>
                <a href="{% url 'App:bot-status' i.id %}">{{i}}</a>
              </li>
              {% endfor %}
             </ul>
          </li>

          <li><a href="{% url 'AccountsApp:logout' %}" class="nav-link scrollto ">Logout</a></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->
    </div>
  </header><!-- End Header -->

  <main id="main">   
   

    <section class="inner-page">
      <p>
        {% block content %}
        
          {% endblock %}
        </p>
      </div>
    </section>

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer">   

    <div class="container d-md-flex py-4">
      <div class="me-md-auto text-center text-md-start">
        <div class="copyright">
          &copy; 2021 &nbsp;<strong><span> Vistan Nextgen Pvt Ltd</span></strong>. All Rights Reserved
        </div>  
      </div>
      <div class="social-links text-center text-md-right pt-3 pt-md-0">
        <a href="https://twitter.com/nextgenvistan" class="twitter"><i class="bx bxl-twitter"></i></a>
        <a href="https://www.facebook.com/vistannextgen1/" class="facebook"><i class="bx bxl-facebook"></i></a>
        <a href="https://www.instagram.com/vistannextgen/" class="instagram"><i class="bx bxl-instagram"></i></a>
        <a href="https://in.linkedin.com/company/vistannextgen" class="linkedin"><i class="bx bxl-linkedin"></i></a>
      </div>
    </div>
  </footer><!-- End Footer -->

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static "assets/vendor/aos/aos.js" %}"></script>
  <script src="{% static "assets/vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
  <script src="{% static "assets/vendor/glightbox/js/glightbox.min.js" %}"></script>
  <script src="{% static "assets/vendor/isotope-layout/isotope.pkgd.min.js" %}"></script>
  <script src="{% static "assets/vendor/php-email-form/validate.js" %}"></script>
  <script src="{% static "assets/vendor/purecounter/purecounter.js" %}"></script>
  <script src="{% static "assets/vendor/swiper/swiper-bundle.min.js" %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static "assets/js/main.js" %}"></script>

{% block js %}
{% endblock %}
</body>

</html>