App/urls.py
from django.urls import path
from . import views

app_name = 'App'

urlpatterns = [
    path('', views.HomeView, name = 'home'),
    path('bot/<str:id>', views.SelectBotView, name = 'select-bot'),
    path('speaker/on/<str:id>', views.SpeakerONStautsView, name = 'speaker-on'),
    path('speaker/off/<str:id>', views.SpeakerOFFStatusView, name = 'speaker-off'),

    path('vbot/<str:id>', views.SelectVBBotView, name = 'select-vbot'),
    path('bot-status/<str:id>', views.Botstatus, name = 'bot-status'),

]

WB_Project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('AccountsApp.urls')),
    path('app/', include('App.urls')),
    path('api/', include('api.urls'))
]

App/templates/App/VB_detail.html
{% extends 'base.html' %}
{% load static %}

{% load static %}

{% block content %}
<div class="container">
    <div class="section-title">
        <h2>{{b.bot_name}}</h2>
    </div>  

    <div class="container">
        <div class="card">
            <div class="card-header">
            {{b.bot_name|title}}
            </div>
            <div class="card-body">
            <br><br>
            <div class="row">
                <div class="col-1"></div>
                <div class="col-sm-3">
                    <div>
                        <img src="/static{{b.image.url}}" alt="{{b.name}}" style = "width:100%; height: auto;">
                    </div>
                </div>
                <div class="col-sm-6">
                    <h3>{{b.bot_name|title}}</h3><br>
                    <h5>Voice Bot is Activated Successfully.</span></h5>
                    <br>
                    <br>
                    


                    <a href="{% url 'App:select-bot' b.id %}" class = "btn btn-success btn-sm">Switch To call</a>
                    <br>
                    <!-- <a href="" class="btn btn-secondary btn-sm">Speaker</a> -->

                </div>
                <div class="col-2"></div>
            </div>
            </div>
        </div>
    </div>
        
        
</div>

{% endblock %}

App/templates/App/bot_detail.html
{% extends 'base.html' %}
{% load static %}

{% load static %}

{% block content %}
<div class="container">
    <div class="section-title">
        <h2>{{b.bot_name}}</h2>
    </div>  

    <div class="container">
        <div class="card">
            <div class="card-header">
            {{b.bot_name|title}}
            </div>
            <div class="card-body">
            <br><br>
            <div class="row">
                <div class="col-1"></div>
                <div class="col-sm-3">
                    <div>
                        <img src="/static{{b.image.url}}" alt="{{b.name}}" style = "width:100%; height: auto;">
                    </div>
                </div>
                <div class="col-sm-6">
                    <!-- <h3>{{b.bot_name|title}}</h3><br> -->
                    <form method = "POST">
                        {% csrf_token %}
                        <div class="form-outline mb-3">
                            <label class="form-label" for="form3Example3">Mobile No</label><br>
        
                            <input type="text" id="" class="form-control form-control-md" required placeholder="Enter Mobile Number" name = "mob_no" /> <br>

                            <button name = 'call_button' type="submit" class="btn btn-md btn-secondary">&nbsp;&nbsp;&nbsp; Call&nbsp;&nbsp;&nbsp;&nbsp;</button>
                        </div>
                    </form>
                    <br>
                    <form>
                        <div class="form-outline mb-3">
                            <label class="form-label" for="form3Example3">Voice Bot</label><br>
                                <a href="{% url 'App:select-vbot' b.id %}" class="btn btn-warning btn-md">Voice Bot Mode</a>
                    </form>
                </div>
                <div class="col-2"></div>
            </div>
            </div>
        </div>
    </div>
        
        
</div>

{% endblock %}

App/templates/App/call_detail.html
{% extends 'base.html' %}
{% load static %}

{% load static %}

{% block content %}
<div class="container">
    <div class="section-title">
        <h2>{{b.bot_name}}</h2>
    </div>  

    <div class="container">
        <div class="card">
            <div class="card-header">
            {{b.bot_name|title}}
            </div>
            <div class="card-body">
            <br><br>
            <div class="row">
                <div class="col-1"></div>
                <div class="col-sm-3">
                    <div>
                        <img src="/static{{b.image.url}}" alt="{{b.name}}" style = "width:100%; height: auto;">
                    </div>
                </div>
                <div class="col-sm-6">
                    <h3>{{b.bot_name|title}}</h3><br>
                    <h5>Bot is communicating with : <span  style="color: orangered;">{{mob_no}}</span></h5>
                    <br>
                    <br>
                    <a href="{% url 'App:speaker-on' b.id%}" 
                       class = "btn btn-danger btn-sm">
                       Speaker on
                    </a>

                    <a href="{% url 'App:speaker-off' b.id%}" 
                       class = "btn btn-info btn-sm">
                       Speaker Off
                    </a>

                    <br><br>
                    <a href="{% url 'App:select-bot' b.id %}" class = "btn btn-success btn-sm">Call Another Number</a>
                    <br>
                    <!-- <a href="" class="btn btn-secondary btn-sm">Speaker</a> -->

                </div>
                <div class="col-2"></div>
            </div>
            </div>
        </div>
    </div>
        
        
</div>

{% endblock %}

App/templates/App/home.html
{% extends 'base.html' %}
{% load static %}

{% load static %}

{% block content %}
<div class="container">
    <div class="section-title">
        <h2>Available Robots</h2>
    </div>  
        
        <div class="row">
            {% for i in cp_bots %}
            
            <div class="col-sm-2">
                <div class="card">
                    <div>
                        <img src="/static{{i.image.url}}" alt="{{i.name}}" style = "width:100%; height: auto;">
                    </div>
                    <div class="card-header text-center">
                        <a href="{% url 'App:select-bot' i.id %}"><b>{{i.bot_name}}</b></a>
                                    </div>
                    <div class="card-info text-center">
                        <span>{{i.bot_color}}</span><br>
                                           
                    </div>
                </div><br>
            </div>            
            {% endfor %}

            
        </div>    
</div><br><br>

{% endblock %}